GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/629605426e9a29bc279e0da3

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "30022999"
}

###

